/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as CliAuthRouteImport } from './routes/cli.auth'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrashRouteImport } from './routes/dashboard/trash'
import { Route as DashboardDocumentsIdRouteImport } from './routes/dashboard/documents.$id'
import { Route as DashboardDocumentsIdDiffRouteImport } from './routes/dashboard/documents.$id_.diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/dashboard/trash',
  path: '/dashboard/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentsIdRoute = DashboardDocumentsIdRouteImport.update({
  id: '/dashboard/documents/$id',
  path: '/dashboard/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentsIdDiffRoute =
  DashboardDocumentsIdDiffRouteImport.update({
    id: '/dashboard/documents/$id_/diff',
    path: '/dashboard/documents/$id/diff',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/cli/auth': typeof CliAuthRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/documents/$id/diff': typeof DashboardDocumentsIdDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/cli/auth': typeof CliAuthRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/documents/$id/diff': typeof DashboardDocumentsIdDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/workspace': typeof WorkspaceRoute
  '/cli/auth': typeof CliAuthRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/documents/$id': typeof DashboardDocumentsIdRoute
  '/dashboard/documents/$id_/diff': typeof DashboardDocumentsIdDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/workspace'
    | '/cli/auth'
    | '/dashboard/trash'
    | '/dashboard/'
    | '/dashboard/documents/$id'
    | '/dashboard/documents/$id/diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/workspace'
    | '/cli/auth'
    | '/dashboard/trash'
    | '/dashboard'
    | '/dashboard/documents/$id'
    | '/dashboard/documents/$id/diff'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/workspace'
    | '/cli/auth'
    | '/dashboard/trash'
    | '/dashboard/'
    | '/dashboard/documents/$id'
    | '/dashboard/documents/$id_/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  WorkspaceRoute: typeof WorkspaceRoute
  CliAuthRoute: typeof CliAuthRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDocumentsIdRoute: typeof DashboardDocumentsIdRoute
  DashboardDocumentsIdDiffRoute: typeof DashboardDocumentsIdDiffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/dashboard/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/documents/$id': {
      id: '/dashboard/documents/$id'
      path: '/dashboard/documents/$id'
      fullPath: '/dashboard/documents/$id'
      preLoaderRoute: typeof DashboardDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/documents/$id_/diff': {
      id: '/dashboard/documents/$id_/diff'
      path: '/dashboard/documents/$id/diff'
      fullPath: '/dashboard/documents/$id/diff'
      preLoaderRoute: typeof DashboardDocumentsIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  WorkspaceRoute: WorkspaceRoute,
  CliAuthRoute: CliAuthRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDocumentsIdRoute: DashboardDocumentsIdRoute,
  DashboardDocumentsIdDiffRoute: DashboardDocumentsIdDiffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
